### ISSUE TITLE
测试数据

### ISSUE THREAD

**Issue by defineconst** [newyusiyu1987/fy3DModelControllib#1]
可以放一份测试演示数据吗？谢谢

**Comment by newyusiyu1987** [comment]
请问你是？最近电脑系统出问题了，传不上去，如果需要的话，可以发给你！



---原始邮件---
发件人: "defineconst"<notifications@github.com&gt;
发送时间: 2020年5月6日(周三) 上午9:23
收件人: "newyusiyu1987/fy3DModelControllib"<fy3DModelControllib@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [newyusiyu1987/fy3DModelControllib] 测试数据 (#1)




 
可以放一份测试演示数据吗？谢谢

**Comment by defineconst** [comment]
谢谢！
